### ISSUE TITLE
Ayrıntılı Guide?

### ISSUE THREAD

**Issue by xxx02** [atillayurtseven/AlgoLab#1]
Emir gönderme ve düzenleme için de örnek hazırlanacak mı acaba?
Bir de sms olayını her seferinde yapmamız mı gerekiyor? Bunu nasıl aşabiliriz?

**Comment by atillayurtseven** [comment]
Evet her seferinde yapmak gerekiyor ancak keepalive ekleyeceğim. Ekleyince detayları yazarım. Algolab müsade ederse detaylı bir doc yazarım.

**Comment by alitekdemir** [comment]
Keep a live SessionRefresh() ile yapılıyor zannedersem.

Burada paylaştığınız örnek kodu aşağıdaki şekilde kendimce düzenledim.
Liste içerisindeki sembollerin son değerlerini sırayla ekrana basıyor.
While ile süre kontrolü eklenerek döngü kurulursa belirlenen periyotta sürekli verileri ekrana getirecektir.
Başlangıç için faydalı olacaktır diye paylaşıyorum.

```python
from algolab import AlgoLab
import pandas as pd
import json

with open("config.json", "r") as config_file:
    credentials = json.load(config_file)
API_KEY = credentials["API_KEY"]
USERNAME = credentials["USERNAME"]
PASSWORD = credentials["PASSWORD"]


def get_stock_data(symbol, period):
    candle = session.GetCandleData(symbol, period)
    if candle.get("Success") and candle.get("Content"):
        content = candle["Content"]
        df = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close"],
                          data=content)
        df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%dT%H:%M:%S")
        return df


if __name__ == "__main__":
    symbols = ["OZRDN", "KRDMD", "ASELS"]
    period = "60"
    session = AlgoLab(api_key=API_KEY, username=USERNAME, password=PASSWORD)
    if session.LoginUser() and session.LoginUserControl():
        for symbol in symbols:
            df = get_stock_data(symbol, period)
            print(f"{symbol} df mum sayısı : {len(df)}")
            print(df.tail(1))
```

Aynı klasörde aşağıdaki gibi `config.json` adında bir dosya olması gerekiyor.

```json
{
  "API_KEY": "API-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "USERNAME": "TC_Kimlik_No",
  "PASSWORD": "XXXXXX"
}
```

**Comment by alitekdemir** [comment]
Bu arada az önce öğrendim, GetCandleData günde 1 defa kullanılabiliyormuş! Maalesef. WebSocket kullanılması gerekiyormuş. Kodda başka fonksiyonlar da hazırlamak lazım.

**Comment by xxx02** [comment]
> Keep a live SessionRefresh() ile yapılıyor zannedersem.
> 
> Burada paylaştığınız örnek kodu aşağıdaki şekilde kendimce düzenledim. Liste içerisindeki sembollerin son değerlerini sırayla ekrana basıyor. While ile süre kontrolü eklenerek döngü kurulursa belirlenen periyotta sürekli verileri ekrana getirecektir. Başlangıç için faydalı olacaktır diye paylaşıyorum.
> 
> ```python
> from algolab import AlgoLab
> import pandas as pd
> import json
> 
> with open("config.json", "r") as config_file:
>     credentials = json.load(config_file)
> API_KEY = credentials["API_KEY"]
> USERNAME = credentials["USERNAME"]
> PASSWORD = credentials["PASSWORD"]
> 
> 
> def get_stock_data(symbol, period):
>     candle = session.GetCandleData(symbol, period)
>     if candle.get("Success") and candle.get("Content"):
>         content = candle["Content"]
>         df = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close"],
>                           data=content)
>         df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%dT%H:%M:%S")
>         return df
> 
> 
> if __name__ == "__main__":
>     symbols = ["OZRDN", "KRDMD", "ASELS"]
>     period = "60"
>     session = AlgoLab(api_key=API_KEY, username=USERNAME, password=PASSWORD)
>     if session.LoginUser() and session.LoginUserControl():
>         for symbol in symbols:
>             df = get_stock_data(symbol, period)
>             print(f"{symbol} df mum sayısı : {len(df)}")
>             print(df.tail(1))
> ```
> 
> Aynı klasörde aşağıdaki gibi `config.json` adında bir dosya olması gerekiyor.
> 
> ```json
> {
>   "API_KEY": "API-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
>   "USERNAME": "TC_Kimlik_No",
>   "PASSWORD": "XXXXXX"
> }
> ```

Hocam order gönderme nasıl yapılabilir bu konuda bir örnek hazırlayabilir misiniz?
Bir de keepalive yerine flask kullansak belki tekrar tekrar sms girmemize gerek kalmaz.
Aklıma bir de üretilen hash değerini alıp sonraki requestlerde kullanmak geliyor.
API yi robot ile kullanabilmemiz için bir şekilde sms olayını elemine etmemiz gerek.
Binance API kullanımı bu konuda çok rahat. Secret tarzı bir sistem geliştirilemez mi acaba?

Yazdıklarım anlamsız geliyorsa kusuruma bakmayın pythonda çok yeniyim. 😊
Tradingview uygulaması aracılığı ile binance da çalışan bir python robotu kullanıyorum. Benzer sistemi Bist için de kullanmak istiyorum. Gayem bu.

**Comment by atillayurtseven** [comment]
Otomatik login ve keepalive eklendi

**Comment by xxx02** [comment]
> Otomatik login ve keepalive eklendi

Hocam order örneği de gelecek mi?
