### ISSUE TITLE
SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)'))

### ISSUE THREAD

**Issue by huseyinoymak** [atillayurtseven/AlgoLab#9]
Python 3.11.3 kullanıyorum.  Login olmak istediğimde aşağıdaki hata ile karşılaşıyorum. Nasıl çözebiliriz?
LoginUser() fonsiyonunda hata oluştu: HTTPSConnectionPool(host='www.algolab.com.tr', port=443): Max retries exceeded with url: /api/api/LoginUser (Caused by
 SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)')))

**Comment by atillayurtseven** [comment]
Güncel hali dener misiniz? Ayrıca Python klasörü içinde "Install Certificates.command" dosyasını çalıştırıp tekrar deneyin. Mac bilgisayarlarda bu var ancak windowsda var mı emin değilim.

**Comment by huseyinoymak** [comment]
Güncel hali denedim. Maalesef halen sorun devam ediyor. Şimdi de _ssl.c:1006 olarak hata döndürüyor. Windows kullanıcısıyım 64 bit işletim sisteminde visual studio code ile çalışıyorum. evdeki bilgisayarda, farklı bir bilgisayarda da denedim. Çözüme ulaşamadım. certifi kütüphanesi kurulu olmalı ve güncel tutulmalı şeklinde tavsiyeler vardı. kütüphaneyi güncellememe rağmen hata almaya devam ediyorum.

**Comment by huseyinoymak** [comment]
Sorun çözüldü:
requirements.txt içindeki versiyonlardan daha güncel versiyon kurmayınız pycryptodome için. Güncel versiyonlarda sslv3 desteği kaldırıldığı için hata vermekte imiş.
